project:
  type: website
  output-dir: docs

website:
  title: "Projet R – Production d’électricité (Tunisie)"
  navbar:
    left:
      - href: qmd/index.qmd
        text: Accueil
      - href: qmd/report.qmd
        text: Rapport
      - href: slides/slidesR.pdf
        text: Slides
  page-footer:
    left: "Ines Elouaer"
    right: "Capstone R"

format:
  html:
    theme: cosmo
    toc: true
